### ISSUE TITLE
所有接口502

### ISSUE THREAD

**Issue by cuijiudai** [Binaryify/NeteaseCloudMusicApi#1023]
## 环境
- 系统/平台:  mac 

- nodejs 版本: v10.16.0

- API版本: "3.46.1"

## 出现问题
npm install 后
node app.js 

然后调用接口都是 502 ，控制台输出报错:
eg
访问:http://localhost:3000/cellphone/existence/check?phone=17505329953

返回：
> 

**Promise { <pending> }
[ERR] /cellphone/existence/check?phone=17505329953 { status: 502,
  body:
   { code: 502,
     msg:
      { Error: connect ECONNREFUSED 127.0.0.1:1081
          at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
        errno: 'ECONNREFUSED',
        code: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 1081,
        config: [Object],
        request: [Writable],
        response: undefined,
        isAxiosError: true,
        toJSON: [Function: toJSON] } } }
(node:45352) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (/Users/cuijiudai/project/NeteaseCloudMusicApi/node_modules/express/lib/response.js:1123:12)
    at ServerResponse.json (/Users/cuijiudai/project/NeteaseCloudMusicApi/node_modules/express/lib/response.js:260:14)
    at ServerResponse.send (/Users/cuijiudai/project/NeteaseCloudMusicApi/node_modules/express/lib/response.js:158:21)
    at question.then.catch (/Users/cuijiudai/project/NeteaseCloudMusicApi/app.js:105:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:45352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)**

**Comment by Binaryify** [comment]
终端取消掉代理试试

**Comment by xiebruce** [comment]
> 终端取消掉代理试试

卧槽，我说怎么什么接口都502的，竟然是我用npm安装时，终端设置了代理导致的
