### ISSUE TITLE
banner 访问400

### ISSUE THREAD

**Issue by ZANETACK** [Binaryify/NeteaseCloudMusicApi#1037]
/banner?type=0
报错如下：

<html><head><title>Apache Tomcat/7.0.52 - Error report</title><style></style> </head><body><h1>HTTP Status 400 - Required String parameter 'eparams' is not present</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Required String parameter 'eparams' is not present</u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.52</h3></body></html>

解决： 
     把 crypto: linuxapi 换成 crypto: weapi 成功访问

**Comment by Binaryify** [comment]
感谢反馈，下次更新考虑替换掉所有的linuxapi

**Comment by wangyumo85** [comment]
1) 测试登录是否正常
       手机登录 code 应该等于200:
     Error: Request failed with status code 400
      at createError (node_modules\axios\lib\core\createError.js:16:15)
      at settle (node_modules\axios\lib\core\settle.js:17:12)
      at IncomingMessage.handleStreamEnd (node_modules\axios\lib\adapters\http.js:244:11)
      at endReadableNT (_stream_readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
测试时出现这种错误该怎么修改

**Comment by Binaryify** [comment]
@wangyumo85  贴下完整日志截图

**Comment by wangyumo85** [comment]
PS C:\Users\14980\AppData\Roaming\.homeassistant> cd .\NeteaseCloudMusicApi\
PS C:\Users\14980\AppData\Roaming\.homeassistant\NeteaseCloudMusicApi> npm test

> NeteaseCloudMusicApi@3.47.3 test C:\Users\14980\AppData\Roaming\.homeassistant\NeteaseCloudMusicApi
> mocha -r intelli-espower-loader -t 20000 app.test.js --exit

注意: 测试登录需在 test/login.test.js 中填写账号密码!!!


  测试获取歌手专辑列表是否正常
server running @ http://localhost:3000
[OK] /album?id=32311
    √ 数据的 code 应该为200 (324ms)

  测试获取评论是否正常
[OK] /comment/album?id=32311
    √ 数据的 code 应该为200 (358ms)

  测试登录是否正常
[ERR] /login/cellphone?phone=&password= { status: 400, body: { code: 400 } }
    1) 手机登录 code 应该等于200

  测试获取歌词是否正常
[OK] /lyric?id=347230
    √ 数据应该有 lrc 字段 (170ms)

  测试获取歌曲是否正常
[OK] /song/url?id=462791935&br=999000
    √ 歌曲的 url 不应该为空 (209ms)

  测试搜索是否正常
[OK] /search?keywords=海阔天空&type=1
    √ 获取到的数据的 name 应该和搜索关键词一致 (288ms)

  5 passing (3s)
  1 failing

  1) 测试登录是否正常
       手机登录 code 应该等于200:
     Error: Request failed with status code 400
      at createError (node_modules\axios\lib\core\createError.js:16:15)
      at settle (node_modules\axios\lib\core\settle.js:17:12)
      at IncomingMessage.handleStreamEnd (node_modules\axios\lib\adapters\http.js:244:11)
      at endReadableNT (_stream_readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by wangyumo85** [comment]
2020-11-26 15:35:41 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for havcs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-26 15:35:41 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ha-baidu-map which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-26 15:35:41 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=209 from 2020-11-26 07:34:27.080245)
2020-11-26 15:35:43 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ha_cloud_music which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-26 15:35:43 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hf_weather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-26 15:35:44 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for HeWeather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-26 15:35:44 WARNING (MainThread) [custom_components.havcs] [init] Data in your config entry is going to override your configuration.yaml: {'platform': ['aligenie'], 'skill': {}, 'setting': {'broker': 'mqtt.ljr.im', 'port': 28883, 'app_key': 'uA8TbOOFrjniPy64', 'app_secret': 'q,}6M{P3MukcShrG', 'entity_key': ''}, 'device_config': 'ui'}
2020-11-26 15:35:54 ERROR (MainThread) [metno] https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned 
2020-11-26 15:35:54 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 5 seconds
2020-11-26 15:35:54 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "C:\Users\14980\AppData\Roaming\.homeassistant\custom_components\ha_cloud_music\api_music.py", line 37, in login
    if res['code'] == 200:
TypeError: 'NoneType' object is not subscriptable
2020-11-26 15:36:09 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 10 seconds
2020-11-26 15:36:29 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 20 seconds
2020-11-26 15:36:59 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 40 seconds
2020-11-26 15:37:49 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 80 seconds
2020-11-26 15:39:19 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 80 seconds
