### ISSUE TITLE
无法安装 NeteaseCloudMusicApi

### ISSUE THREAD

**Issue by dyl8023** [Binaryify/NeteaseCloudMusicApi#1065]
## 环境
- 系统/平台: linux

- nodejs 版本: 14.15.3

- API版本:未安装

## 出现问题
使用：$ git clone git@github.com:Binaryify/NeteaseCloudMusicApi.git
安装时 提示： -bash: $: command not found
![image](https://user-images.githubusercontent.com/52656767/102741930-8c46f200-434b-11eb-968f-d419def4bea9.png)

## 重现步骤
使用：$ git clone git@github.com:Binaryify/NeteaseCloudMusicApi.git
安装时 提示： -bash: $: command not found

## 期待效果
成功安装

**Comment by Binaryify** [comment]
你多复制了$

**Comment by dyl8023** [comment]
> 你多复制了$

啊 哈哈第一次玩这个 不好意思 我再试试 谢谢

**Comment by dyl8023** [comment]
> 你多复制了$

git clone git@github.com:Binaryify/NeteaseCloudMusicApi.git
Cloning into 'NeteaseCloudMusicApi'...
The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,13.229.188.59' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


==========
请问下这个是什么意思啊？

**Comment by dyl8023** [comment]
[root@iZ0ak0mnd9p3ixZ local]# node -v
v14.15.3
[root@iZ0ak0mnd9p3ixZ local]# git clone git@github.com:Binaryify/NeteaseCloudMusicApi.git
Cloning into 'NeteaseCloudMusicApi'...
The authenticity of host 'github.com (13.229.188.59)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,13.229.188.59' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[root@iZ0ak0mnd9p3ixZ local]# npm -v
6.14.9
[root@iZ0ak0mnd9p3ixZ local]#

**Comment by dyl8023** [comment]
> 你多复制了$

这算是 安装好了吗？？
==================
[root@iZ0ak0mnd9p3ixZ local]# npm install
npm WARN saveError ENOENT: no such file or directory, open '/usr/local/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/package.json'
npm WARN local No description
npm WARN local No repository field.
npm WARN local No README data
npm WARN local No license field.

up to date in 1.381s
found 0 vulnerabilities

[root@iZ0ak0mnd9p3ixZ local]# node app.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/usr/local/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by dyl8023** [comment]
[root@iZ0ak0mnd9p3ixZ NeteaseCloudMusicApi]# node app.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /usr/local/NeteaseCloudMusicApi/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/NeteaseCloudMusicApi/app.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/NeteaseCloudMusicApi/app.js' ]
}

**Comment by dyl8023** [comment]
ran

> 你多复制了$

我要怎么才能开始使用？？？

**Comment by dyl8023** [comment]
已经搭建好啦
已经搭建好啦
已经搭建好啦
已经搭建好啦

**Comment by Binaryify** [comment]
好~

**Comment by Mix-Xie** [comment]
apple@appledembp NeteaseCloudMusicApi % npm start

> NeteaseCloudMusicApi@4.8.9 start
> node app.js

node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'express'
Require stack:
- /Users/apple/developers/NeteaseCloudMusicApi/server.js
- /Users/apple/developers/NeteaseCloudMusicApi/app.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/apple/developers/NeteaseCloudMusicApi/server.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/apple/developers/NeteaseCloudMusicApi/server.js',
    '/Users/apple/developers/NeteaseCloudMusicApi/app.js'
  ]
}
