### ISSUE TITLE
Chrome 访问报错 URIError: URI malformed

### ISSUE THREAD

**Issue by OPTOPIA** [Binaryify/NeteaseCloudMusicApi#1110]
## 环境
- 系统/平台: CentOS7

- nodejs 版本: v14.15.4

- API版本: 4.0.3

## 出现问题
搭建完成后使用chrome\edge浏览器访问接口报错：
```
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at /root/Github/NeteaseCloudMusicApi/app.js:47:9
    at Array.forEach (<anonymous>)
    at /root/Github/NeteaseCloudMusicApi/app.js:42:48
    at Layer.handle [as handle_request] (/root/Github/NeteaseCloudMusicApi/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/Github/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:317:13)
    at /root/Github/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/Github/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:335:12)
    at next (/root/Github/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:275:10)
    at /root/Github/NeteaseCloudMusicApi/app.js:36:54
```
chrome版本 88.0.4324.104

使用IE\手机端访问则正常

---

**Comment by liyang-it** [comment]
我也是不知道咋回事。同问 。不过 这样也没大事，反正api能给其他项目调用就行

**Comment by Binaryify** [comment]
无法重现，是不是url带了什么特殊字符

**Comment by ishelo** [comment]
重现问题

**Comment by ishelo** [comment]
谷歌版本：版本 88.0.4324.150（正式版本）显示 URIError: URI malformed
EDGE版本：版本 88.0.705.63 (官方内部版本) (64 位)显示正常
EDGE版本：版本 88.0.705.68 (官方内部版本) (64 位)显示正常

**Comment by Stephen-AC** [comment]
把浏览器上的cookie清了就可以了

**Comment by Binaryify** [comment]
URL 不要带 %
