### ISSUE TITLE
Windows Server 2016 管理这个项目有什么要求吗？

### ISSUE THREAD

**Issue by gyjcode** [Binaryify/NeteaseCloudMusicApi#1129]
## 环境
- 系统/平台: Windows Server 2016

- nodejs 版本: 10.16.0

- API版本: 4.0.3

## 出现问题
使用的 Windows Server 2016 宝塔面板 PM2 管理器管理的项目，添加项目后报错信息如下：
![项目失败](https://user-images.githubusercontent.com/45870098/107454879-c765e480-6b88-11eb-9da9-1192e1de36db.png)
PM2 重启错误日志如下：
2021-02-10T10:15:10: PM2 log: App [NeteaseCloudMusic:0] starting in -fork mode-
2021-02-10T10:15:10: PM2 log: App [NeteaseCloudMusic:0] online
2021-02-10T10:15:11: PM2 error: Error: spawn node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2021-02-10T10:15:11: PM2 error: Cancelling versioning data parsing

端口号已开启，还需要其他配置吗？

**Comment by JackuXL** [comment]
npm install

**Comment by gyjcode** [comment]
> npm install

试了，不管。应该是面板的问题

**Comment by JackuXL** [comment]
> > npm install
> 
> 试了，不管。应该是面板的问题

我linux用面板都正常

**Comment by JackuXL** [comment]
> > npm install
> 
> 试了，不管。应该是面板的问题

你试试命令 pm2 start app.js
