### ISSUE TITLE
获取的时候报错 麻烦大神帮忙看看

### ISSUE THREAD

**Issue by xingyue234** [Binaryify/NeteaseCloudMusicApi#113]
### 环境
系统:  

nodejs 版本: 6.11.0

### 后台报错内容：
Error: connect ETIMEDOUT 103.211.228.142:80
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

**Comment by Binaryify** [comment]
能否提供具体的运行环境,包括服务器相关信息
