### ISSUE TITLE
<不按照模版格式或者删除模版信息将得不到处理,确认看完了调用前须知再发 issues>

### ISSUE THREAD

**Issue by Enough1998** [Binaryify/NeteaseCloudMusicApi#1195]
Chrome 上调用出现url解密失败问题

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at /www/wwwroot/NeteaseCloudMusicApi/app.js:48:9
    at Array.forEach (<anonymous>)
    at /www/wwwroot/NeteaseCloudMusicApi/app.js:42:48
    at Layer.handle [as handle_request] (/www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:317:13)
    at /www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:335:12)
    at next (/www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:275:10)
    at /www/wwwroot/NeteaseCloudMusicApi/app.js:36:54

**Comment by Enough1998** [comment]
> Chrome 上调用出现url解密失败问题
> 
> URIError: URI malformed
> at decodeURIComponent ()
> at /www/wwwroot/NeteaseCloudMusicApi/app.js:48:9
> at Array.forEach ()
> at /www/wwwroot/NeteaseCloudMusicApi/app.js:42:48
> at Layer.handle [as handle_request] (/www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:317:13)
> at /www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:335:12)
> at next (/www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:275:10)
> at /www/wwwroot/NeteaseCloudMusicApi/app.js:36:54
