### ISSUE TITLE
运行后访问地址出现错误

### ISSUE THREAD

**Issue by Wlisfes** [Binaryify/NeteaseCloudMusicApi#1211]
## 环境
- 系统/平台: CentOS 8.2 64位--aliyun

- nodejs 版本: v14.16.1

- API版本: 4.0.10

## 出现问题
npm start 运行后正常   安全组已开放3000端口  浏览器用ip访问爆错

### 以下是浏览器访问3000端口出现在浏览器里面的爆错内容
`
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at /www/wwwroot/api.lisfes.cn/CloudMusicApi/app.js:47:9
    at Array.forEach (<anonymous>)
    at /www/wwwroot/api.lisfes.cn/CloudMusicApi/app.js:42:48
    at Layer.handle [as handle_request] (/www/wwwroot/api.lisfes.cn/CloudMusicApi/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/www/wwwroot/api.lisfes.cn/CloudMusicApi/node_modules/express/lib/router/index.js:317:13)
    at /www/wwwroot/api.lisfes.cn/CloudMusicApi/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/www/wwwroot/api.lisfes.cn/CloudMusicApi/node_modules/express/lib/router/index.js:335:12)
    at next (/www/wwwroot/api.lisfes.cn/CloudMusicApi/node_modules/express/lib/router/index.js:275:10)
    at /www/wwwroot/api.lisfes.cn/CloudMusicApi/app.js:36:54
`

### 以下是运行面板出现的错误
![](https://oss.lisfes.cn/upload/1619259142014.jpg)

## 期待效果
期待正常进入主页

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Wlisfes** [comment]
不好意思，我找到问题了，是缓存导致！
