### ISSUE TITLE
阿里云linux起服务一直报错，之前好好的

### ISSUE THREAD

**Issue by caim18340** [Binaryify/NeteaseCloudMusicApi#1232]
## 环境
- 系统/平台: <Alibaba Cloud Linux 2.1903 LTS 64位>

- nodejs 版本: <6.17.1>

- API版本: <最新版本>

## 出现问题
起服务报错
[root@iZuf6ecpsnuw55hf6b4ksuZ NeteaseCloudMusicApi]# node app.js
/root/NeteaseCloudMusicApi/app.js:18
      )
      ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

## 重现步骤
git clone https://github.com/Binaryify/NeteaseCloudMusicApi.git
cd NeteaseCloudMusicApi
npm i
node app.js报错起不了服务 

## 期待效果
能起服务

**Comment by Binaryify** [comment]
需要 NodeJS 8.12+ 环境
