### ISSUE TITLE
访问502 SSL问题

### ISSUE THREAD

**Issue by Coloryr** [Binaryify/NeteaseCloudMusicApi#1256]
## 环境
- 系统/平台: windows server 2019

- nodejs 版本: 14.7.0

- API版本: 4.0.16
## 出现问题
```
[ERR] /lyric?id=414118123 {
  status: 502,
  body: {
    code: 502,
    msg: Error: read ECONNRESET
        at TLSWrap.onStreamRead (internal/stream_base_commons.js:207:27) {
      errno: -4077,
      code: 'ECONNRESET',
      syscall: 'read',
      config: [Object],
      request: [Writable],
      response: undefined,
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }
  }
}
(node:38236) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (D:\NeteaseCloudMusicApi\node_modules\express\lib\response.js:1123:12)
    at ServerResponse.json (D:\NeteaseCloudMusicApi\node_modules\express\lib\response.js:260:14)
    at ServerResponse.send (D:\NeteaseCloudMusicApi\node_modules\express\lib\response.js:158:21)
    at D:\NeteaseCloudMusicApi\app.js:106:37
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:38236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

## 重现步骤
访问就出现

## 尝试解决
我把所有的https改成http就没出问题了

**Comment by youmu1** [comment]
您好，您遇到的502问题解决了么？

**Comment by Coloryr** [comment]
没有解决

**Comment by ZevveZ** [comment]
新版已经没有问题了，上传成功了，😄

**Comment by lijianbo2004** [comment]
我是今天安装的,还是报502啊

[]ERR] /banner {                                                                                                                                                                                                       status: 502,                                                                                                                                                                                                        body: {                                                                                                                                                                                                               code: 502,                                                                                                                                                                                                          msg: Error: read ECONNRESET                                                                                                                                                                                             at TLSWrap.onStreamRead (node:internal/stream_base_commons:211:20) {                                                                                                                                              errno: -104,                                                                                                                                                                                                        code: 'ECONNRESET',                                                                                                                                                                                                 syscall: 'read',                                                                                                                                                                                                    config: [Object],                                                                                                                                                                                                   request: [Writable],                                                                                                                                                                                                response: undefined,                                                                                                                                                                                                isAxiosError: true,                                                                                                                                                                                                 toJSON: [Function: toJSON]                                                                                                                                                                                        }                                                                                                                                                                                                                 }                                                                                                                                                                                                                 }                                                                                                                                                                                                                   {                                                                                                                                                                                                                     status: 502,                                                                                                                                                                                                        body: {                                                                                                                                                                                                               code: 502,                                                                                                                                                                                                          msg: Error: read ECONNRESET                                                                                                                                                                                             at TLSWrap.onStreamRead (node:internal/stream_base_commons:211:20) {                                                                                                                                              errno: -104,                                                                                                                                                                                                        code: 'ECONNRESET',                                                                                                                                                                                                 syscall: 'read',                                                                                                                                                                                                    config: [Object],                                                                                                                                                                                                   request: [Writable],                                                                                                                                                                                                response: undefined,                                                                                                                                                                                                isAxiosError: true,                                                                                                                                                                                                 toJSON: [Function: toJSON]                                                                                                                                                                                        }                                                                                                                                                                                                                 },                                                                                                                                                                                                                  cookie: []                                                                                                                                                                                                        }                                                                                                                                                                                                                   /home/vagrant/code/NeteaseCloudMusicApi-master/node_modules/express/lib/response.js:1123                                                                                                                                : JSON.stringify(value);                                                                                                                                                                                                   ^                                                                                                                                                                                                                                                                                                                                                                                                                            TypeError: Converting circular structure to JSON                                                                                                                                                                        --> starting at object with constructor 'Object'                                                                                                                                                                    \|     property 'httpsAgent' -> object with constructor 'Agent'                                                                                                                                                      \|     property 'sockets' -> object with constructor 'Object'                                                                                                                                                        \|     ...                                                                                                                                                                                                           \|     property 'errored' -> object with constructor 'Object'                                                                                                                                                        --- property 'config' closes the circle                                                                                                                                                                             at JSON.stringify ()                                                                                                                                                                                     at stringify (/home/vagrant/code/NeteaseCloudMusicApi-master/node_modules/express/lib/response.js:1123:12)                                                                                                          at ServerResponse.json (/home/vagrant/code/NeteaseCloudMusicApi-master/node_modules/express/lib/response.js:260:14)                                                                                                 at ServerResponse.send (/home/vagrant/code/NeteaseCloudMusicApi-master/node_modules/express/lib/response.js:158:21)                                                                                                 at /home/vagrant/code/NeteaseCloudMusicApi-master/app.js:122:37                                                                                                                                                     at processTicksAndRejections (node:internal/process/task_queues:96:5)
--



</body>
<!--EndFragment--></html>

**Comment by Ayerfei** [comment]
这个可能是网络问题，我用的公司内网，对网址有限制，所以不能访问到，切换到自己的网络就不会报错了。

**Comment by lijianbo2004** [comment]
谢谢,确实是这样的


| |
李建波
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年8月20日 ***@***.***> 写道：

这个可能是网络问题，我用的公司内网，对网址有限制，所以不能访问到，切换到自己的网络就不会报错了。

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
