### ISSUE TITLE
任意请求都出现Error: read ECONNRESET错误，程序中止

### ISSUE THREAD

**Issue by selectersky** [Binaryify/NeteaseCloudMusicApi#128]
### 环境
系统:  
mac os 10.12.6

nodejs 版本:
v8.9.0

### 出现问题
任意请求都出现如下错误，程序中止：

```
$ node app.js
server running @3000
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
```
### 期待效果

**Comment by selectersky** [comment]
确认是网络问题

**Comment by Hjw52** [comment]
域网络不行是吗
