### ISSUE TITLE
手机登录接口无法使用: TypeError: {} is not a function

### ISSUE THREAD

**Issue by Deteriorator** [Binaryify/NeteaseCloudMusicApi#1319]
## 环境
- 系统/平台: Windows 10 

- nodejs 版本: v14.15.4

- API版本: 4.0.18 

## 出现问题
调用手机登录接口出现问题，console 报错如下 TypeError: {} is not a function ：
```
❯ node .\app.js
server running @ http://localhost:3000
TypeError: {} is not a function
    at D:\SourceCode\Projects\node\NeteaseCloudMusicApi\app.js:44:3
    at Layer.handle [as handle_request] (D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:317:13)
    at D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:335:12)
    at next (D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:275:10)
    at D:\SourceCode\Projects\node\NeteaseCloudMusicApi\app.js:37:54
    at Layer.handle [as handle_request] (D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:317:13)
    at D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:284:7
TypeError: {} is not a function
    at D:\SourceCode\Projects\node\NeteaseCloudMusicApi\app.js:44:3
    at Layer.handle [as handle_request] (D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:317:13)
    at D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:335:12)
    at next (D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:275:10)
    at D:\SourceCode\Projects\node\NeteaseCloudMusicApi\app.js:37:54
    at Layer.handle [as handle_request] (D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:317:13)
    at D:\SourceCode\Projects\node\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:284:7
```

## 重现步骤
我使用 Python 调用手机登录接口，出现了上述步骤的错误信息，同时拿到的 response 状态码是 500
![image](https://user-images.githubusercontent.com/31269745/128798901-42b5907b-ed56-4d7e-bf96-4e361c661fa5.png)

## 期待效果
能正常使用

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by 2415091026** [comment]
这个问题解决了吗

**Comment by Binaryify** [comment]
response 打印出来是啥

**Comment by Deteriorator** [comment]
> response 打印出来是啥

response 是 None，不过这个 pr  #1317 修复了

**Comment by Deteriorator** [comment]
> 这个问题解决了吗

我这边测试，已经修复了

**Comment by Binaryify** [comment]
好
