### ISSUE TITLE
没规律地报这个错误Error: read ECONNRESET，服务会停止

### ISSUE THREAD

**Issue by kevinvane** [Binaryify/NeteaseCloudMusicApi#132]
### 环境
系统:  
ubuntu 16.04

网络环境：
局域网

nodejs 版本:
v8.1.3
### 出现问题
客户端主动断开连接，出现以下错误
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:610:25)
```
### 重现步骤

暂无找到重现步骤
网络上有一种说法：客户端主动中断请求会报这个错

### 期待效果
程序不会死

**Comment by Binaryify** [comment]
暂时不知道什么原因,不过你可以用 pm2 管理进程,会自动重启服务

**Comment by kevinvane** [comment]
ok
