### ISSUE TITLE
/playlist/detail接口登录后仍无法正常获取喜欢的音乐列表

### ISSUE THREAD

**Issue by memset0** [Binaryify/NeteaseCloudMusicApi#1346]
登录后访问 `xxx喜欢的音乐` 对应的歌单 id，API 返回 400 Bad Request。

如果将 id 换为普通歌单，则不会出现该问题。

```plain
(node:93796) UnhandledPromiseRejectionWarning: Error: Bad Request
    at Request.callback (D:\Git\memset0\node_modules\superagent\src\node\index.js:879:15)
    at fn (D:\Git\memset0\node_modules\superagent\src\node\index.js:1130:18)
    at IncomingMessage.<anonymous> (D:\Git\memset0\node_modules\superagent\src\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by SD-Gaming** [comment]
确实获取不到结果，推测是网易对喜欢的音乐的请求又增加了限制，造成登陆后依然无法直接获取

**Comment by Binaryify** [comment]
无法重现
![image](https://user-images.githubusercontent.com/12221718/167283787-e9ebb7a4-9d97-4685-8b22-b0d970e47015.png)

**Comment by SD-Gaming** [comment]
找到问题了，与本库无关系

**Comment by simin-xxm** [comment]
> 找到问题了，与本库无关系

大佬方便说下是什么问题吗

**Comment by SD-Gaming** [comment]
> > 找到问题了，与本库无关系
> 
> 大佬方便说下是什么问题吗

我使用的一个库，它依赖了本项目。
原因是那个库没有处理好超过一定数目（比如大于1k首）的【我喜欢的音乐】List，抛了异常
