### ISSUE TITLE
pc谷歌浏览器下调用接口会显示URIError: URI malformed

### ISSUE THREAD

**Issue by ike-yu-byte** [Binaryify/NeteaseCloudMusicApi#1347]
谷歌浏览器下调用接口出错  
具体情况如下：
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at /www/wwwroot/NeteaseCloudMusicApi/app.js:48:7
    at Array.forEach (<anonymous>)
    at /www/wwwroot/NeteaseCloudMusicApi/app.js:44:58
    at Layer.handle [as handle_request] (/www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:317:13)
    at /www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:335:12)
    at next (/www/wwwroot/NeteaseCloudMusicApi/node_modules/express/lib/router/index.js:275:10)
    at /www/wwwroot/NeteaseCloudMusicApi/app.js:37:54

**Comment by Binaryify** [comment]
应该好了
