### ISSUE TITLE
爬取数据总是中断，报error 502怎么解决？

### ISSUE THREAD

**Issue by Chuan1997** [Binaryify/NeteaseCloudMusicApi#1364]
## 环境
- 系统/平台: <win 10>

- nodejs 版本: <8.12>

- API版本: <4.0.23>

## 出现问题
<在爬取用户收藏的歌单信息时，大概每爬取几百个便会中断，试了之前issue里提出的方法，但都没有作用>

## 重现步骤
<[OK] /user/playlist?uid=248982133
[OK] /user/playlist?uid=3296716448
[OK] /user/playlist?uid=489956781
[ERR] /user/playlist?uid=1353566276 { status: 502,
  body:
   { code: 502,
     msg:
      { Error: read ECONNRESET
    at TLSWrap.onread (net.js:622:25)
        errno: 'ECONNRESET',
        code: 'ECONNRESET',
        syscall: 'read',
        config: [Object],
        request: [Object],
        response: undefined,
        isAxiosError: true,
        toJSON: [Function: toJSON] } } }
(node:21192) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (D:\Study\reproduction\新建文件夹\NeteaseCloudMusicApi\node_modules\express\lib\response.js:1123:12)
    at ServerResponse.json (D:\Study\reproduction\新建文件夹\NeteaseCloudMusicApi\node_modules\express\lib\response.js:260:14)
    at ServerResponse.send (D:\Study\reproduction\新建文件夹\NeteaseCloudMusicApi\node_modules\express\lib\response.js:158:21)
    at question.then.catch (D:\Study\reproduction\新建文件夹\NeteaseCloudMusicApi\app.js:133:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:21192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a
catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will termina
te the Node.js process with a non-zero exit code.
>

## 期待效果
<希望能连续地爬取数据>

**Comment by king-of-hxx** [comment]
我现在也是这个问题，本地启动服务，一请求数据就会报502错误

**Comment by y1713375484** [comment]
你们最后怎么解决的，貌似是连接超时断开连接了
