### ISSUE TITLE
登录后获取歌单信息显示未登录

### ISSUE THREAD

**Issue by zhouguannan** [Binaryify/NeteaseCloudMusicApi#1396]
## 环境
- 系统/平台: Archlinux 服务跑在本地

- nodejs 版本:16.11.1

- API版本: 4.0.23

## 出现问题
使用python调用获取歌单详情api出错：code20001登录后才可查看
报错：
```
╭─     ~/Documents/Code/netease-cloud-music-tui                                                                                                             ✔  1m 57s    16:28:01   ─╮
╰─ python debug.py                                                                                                                                                                           ─╯
[OK] /login/cellphone?phone=17710362897&password=xxxxxx
123456
[ERR] /playlist/detail?id=123456 {
  status: 400,
  body: {
    code: 20001,
    message: '登录后才可查看',
    debugInfo: null,
    data: null,
    failData: null,
    msg: '登录后才可查看'
  }
}
Traceback (most recent call last):
  File "/home/kevin/Documents/Code/netease-cloud-music-tui/debug.py", line 32, in <module>
    print(get_playlist_name(a))
  File "/home/kevin/Documents/Code/netease-cloud-music-tui/debug.py", line 23, in get_playlist_name
    return decoded['playlist']['name']
KeyError: 'playlist'
```
python代码：
```python
import requests
import time
import os 
import _thread
import config
import json

def open_server(text1,text2):
    os.chdir("NeteaseCloudMusicApi")
    print(text1+text2)
    os.system("node app.js")

def start_server():
    _thread.start_new_thread(open_server,("Server", "started"))

def phone_login():
    resp = requests.get("http://localhost:3000/login/cellphone?phone=" + config.phone + "&password=" + config.passwd)
    return resp.text

def get_playlist_name(playlist_id):
    resp = requests.get("http://localhost:3000/playlist/detail?id="+str(playlist_id))
    decoded = json.loads(resp.text)
    return decoded['playlist']['name']

try:
    resp = phone_login()
except requests.exceptions.ConnectionError:
    start_server()
    time.sleep(2)
    resp = phone_login()
a = input()
print(get_playlist_name(a))
```

## 重现步骤
运行代码，输入123456
## 期待效果
返回歌单名字  

---

**Comment by zhouguannan** [comment]
是cookie的问题，close了
