### ISSUE TITLE
本地运行的最新版本请求一直报502的错误，好长时间了，还希望大佬能帮我一下

### ISSUE THREAD

**Issue by king-of-hxx** [Binaryify/NeteaseCloudMusicApi#1447]
## 环境
- 系统/平台: <windows10>

- nodejs 版本: <v14.18.2>

- API版本: <4.2.0>

server running @ http://localhost:3000
[ERR] /personalized/newsong?limit=12 {
  status: 502,
  body: {
    code: 502,
    msg: Error: read ECONNRESET
        at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
      errno: -4077,
      code: 'ECONNRESET',
      syscall: 'read',
      config: [Object],
      request: [Writable],
      response: undefined,
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }
  }
}
(node:61764) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'httpsAgent' -> object with constructor 'Agent'
    |     property 'sockets' -> object with constructor 'Object'
    |     ...
    |     property 'errored' -> object with constructor 'Object'
    --- property 'config' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (D:\个人项目\hxx-master\hxx-master\NeteaseCloudMusicApi\node_modules\express\lib\response.js:1123:12)
    at ServerResponse.json (D:\个人项目\hxx-master\hxx-master\NeteaseCloudMusicApi\node_modules\express\lib\response.js:260:14)
    at ServerResponse.send (D:\个人项目\hxx-master\hxx-master\NeteaseCloudMusicApi\node_modules\express\lib\response.js:158:21)
    at D:\个人项目\hxx-master\hxx-master\NeteaseCloudMusicApi\app.js:134:37
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:61764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:61764) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.  

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by Binaryify** [comment]
你环境变量设了什么代理把
