### ISSUE TITLE
只能访问index主页，请求其他功能状态码502报错

### ISSUE THREAD

**Issue by LIPACEY** [Binaryify/NeteaseCloudMusicApi#1618]
## 环境
- 系统/平台: Windows 11 21H2

- nodejs 版本: <v16.17.1>

- API版本: <4.8.2>

## 出现问题
node app.js运行正常，能正常显示页面，请求搜索等就会报错
[ERR] /search?keywords=海阔天空 {
  status: 502,
  body: {
    code: 502,
    msg: Error: read ECONNRESET
        at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
      errno: -4077,
      code: 'ECONNRESET',
      syscall: 'read',
      config: [Object],
      request: [Writable],
      response: undefined,
      isAxiosError: true,
      toJSON: [Function: toJSON]
    }
  }
}
E:\Reptile\Music\NeteaseCloudMusicApi-master\node_modules\express\lib\response.js:1123
    : JSON.stringify(value);
           ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'httpsAgent' -> object with constructor 'Agent'
    |     property 'sockets' -> object with constructor 'Object'
    |     ...
    |     property 'errored' -> object with constructor 'Object'
    --- property 'config' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (E:\Reptile\Music\NeteaseCloudMusicApi-master\node_modules\express\lib\response.js:1123:12)
    at ServerResponse.json (E:\Reptile\Music\NeteaseCloudMusicApi-master\node_modules\express\lib\response.js:260:14)
    at ServerResponse.send (E:\Reptile\Music\NeteaseCloudMusicApi-master\node_modules\express\lib\response.js:158:21)
    at E:\Reptile\Music\NeteaseCloudMusicApi-master\server.js:270:43
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

## 重现步骤
![微信图片_20220927170410](https://user-images.githubusercontent.com/96162063/192484195-e804ce6c-d032-40ff-8418-d14d4c914e64.png)
![微信图片_20220927170430](https://user-images.githubusercontent.com/96162063/192484221-d9235a02-d05b-414e-a556-f4b2e75ec4c3.png)
![微信图片_20220927170448](https://user-images.githubusercontent.com/96162063/192485544-e58ae20b-11c8-4c82-ba5c-461b42652cad.png)

## 期待效果
功能能够正常运行 

---

**Comment by Platapoop** [comment]
I had a friend that encountered the same thing. Hopefully this helps you.

Go to C:\Windows\System32\drivers\etc\
Open hosts
Delete any lines with music.163 or similar
Save (may require Administrator)
Try running CloudApi again.

**Comment by 295we** [comment]
我也是兄弟，你解决了吗

**Comment by wanglong-wl** [comment]
我也是兄弟，你解决了吗

**Comment by olbb** [comment]
配hosts换一个music.163.com试试， 我遇到的是海外的服务器dns也会返回海外的cdn地址，访问的时候会报502，换成国内的ip就好了
