### ISSUE TITLE
作为 Node.js 模块直接调用时出现 anonymous_token 文件路径异常

### ISSUE THREAD

**Issue by tabjy** [Binaryify/NeteaseCloudMusicApi#1795]
## 环境
- 系统/平台: Linux

- nodejs 版本: v18.12.1 LTS

- API版本: 4.11.1

## 出现问题
在 `npm i NeteaseCloudMusicApi` 后通过 Node.js 直接调用（即使用 `require(NeteaseCloudMusicApi)`）时出现 `anonymous_token` 文件路径异常。

创建该文件的 [`app.js:7`](https://github.com/Binaryify/NeteaseCloudMusicApi/blob/52c6021d89bc8051eff3e891c45740895cf9a021/app.js#L7) 将其创建在依赖模块根目录，而 [`request.js:9`](https://github.com/Binaryify/NeteaseCloudMusicApi/blob/52c6021d89bc8051eff3e891c45740895cf9a021/util/request.js#L9) 尝试从 working directory 读取该文件。此错误会在 working directory 非本项目根目录的情况下出现，常见于将本项目要作为 npm 依赖的场景。

## 重现步骤
```sh
kxu@tpp1g4 ~/D/playgrounds> node -v                                                                                                                                                                              130
v18.12.1
kxu@tpp1g4 ~/D/playgrounds> mkdir netease-test
kxu@tpp1g4 ~/D/playgrounds> cd netease-test 
kxu@tpp1g4 ~/D/p/netease-test> npm init               
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help init` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (netease-test) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /home/kxu/Documents/playgrounds/netease-test/package.json:

{
  "name": "netease-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes) 
kxu@tpp1g4 ~/D/p/netease-test> npm i -S NeteaseCloudMusicApi                                    

added 167 packages, and audited 168 packages in 3s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
kxu@tpp1g4 ~/D/p/netease-test> cat ./package.json | grep NeteaseCloudMusicApi                                                                                                                                      1
    "NeteaseCloudMusicApi": "^4.11.1"
kxu@tpp1g4 ~/D/p/netease-test> cat ./package-lock.json | grep NeteaseCloudMusicApi 
        "NeteaseCloudMusicApi": "^4.11.1"
    "node_modules/NeteaseCloudMusicApi": {
      "resolved": "https://registry.npmjs.org/NeteaseCloudMusicApi/-/NeteaseCloudMusicApi-4.11.1.tgz",
        "NeteaseCloudMusicApi": "app.js"
    "NeteaseCloudMusicApi": {
      "resolved": "https://registry.npmjs.org/NeteaseCloudMusicApi/-/NeteaseCloudMusicApi-4.11.1.tgz",
kxu@tpp1g4 ~/D/p/netease-test> echo "require('NeteaseCloudMusicApi')" > index.js  
kxu@tpp1g4 ~/D/p/netease-test> node index.js                
node:internal/fs/utils:348
    throw err;
    ^

Error: ENOENT: no such file or directory, open './anonymous_token'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at Object.<anonymous> (/home/kxu/Documents/playgrounds/netease-test/node_modules/NeteaseCloudMusicApi/util/request.js:9:28)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/kxu/Documents/playgrounds/netease-test/node_modules/NeteaseCloudMusicApi/main.js:4:17) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './anonymous_token'
}

Node.js v18.12.1

```

## 期待效果

在第一次以 `require()` 引用时应在 `main.js` 中使用与 `app.js` 相似的逻辑创建 `anonymous_token`。（目前若非手动运行 `app.js` 否则不会创建此文件。）[`request.js:9`](https://github.com/Binaryify/NeteaseCloudMusicApi/blob/52c6021d89bc8051eff3e891c45740895cf9a021/util/request.js#L9) 应该从与 `main.js` 创建的文件一致的路径读取。

至于 `anonymous_token` 应该放在模块代码根目录（`path.resolve(__dirname, 'anonymous_token')`）还是 working directory 不在本 issue 的讨论范围之内，只要一致即可。但是考虑到此依赖可能被全局安装和只读安装的情况，个人更倾向于后者。

**Comment by Binaryify** [comment]
已修复

**Comment by tabjy** [comment]
> ## 期待效果
> 在第一次以 `require()` 引用时应在 `main.js` 中使用与 `app.js` 相似的逻辑创建 anonymous_token。（目前若非手动运行 app.js 否则不会创建此文件。）

不好貌似意思 v4.12.1 并未解决此问题，请问是否是 non-goal？如果不是是否能 reopen 此 issue？谢谢！

```
kxu@tpp1g4 ~/D/p/netease-test> node index.js                
node:internal/fs/utils:348
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/tmp/anonymous_token'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at Object.<anonymous> (/home/kxu/Documents/playgrounds/netease-test/node_modules/NeteaseCloudMusicApi/util/request.js:11:28)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/kxu/Documents/playgrounds/netease-test/node_modules/NeteaseCloudMusicApi/main.js:4:17) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/tmp/anonymous_token'
}
```

**Comment by Binaryify** [comment]
确实疏漏了

**Comment by Binaryify** [comment]
再看看

**Comment by tabjy** [comment]
确认该问题已修复 十分感谢您的付出！

fixed by 957213b
