### ISSUE TITLE
<不按照模版格式或者删除模版信息将得不到处理,确认看完了调用前须知再发 issues>

### ISSUE THREAD

**Issue by XiejiHuang** [Binaryify/NeteaseCloudMusicApi#1829]
## 环境
- 系统/平台: Windows11

- nodejs 版本: v18.16.0

- API版本: 4.13.5

## 出现问题
<请清晰描述出现的问题,不要使用xxx不行之类的模糊不清的语句,我没有读心术>
1、当不登入账号没有账号cookie时候关于获取歌曲信息的接口全部会报
![LH@L@H` $J~0HJP9@26_QOS](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/147133877/54f0b909-31e9-44f2-8fb9-aa288372f481)

比如/playlist/track/all?id，/search?keywords
等等关于歌曲信息的接口都会报这个错，
登入匿名账号也不行只有登入网易云的账号才不会报这个错误，
但是我发现4.5.8没有这个问题但是4.5.8版本的登入接口会报这个错误
2、以及注册接口会报错
手机号和验证码昵称已经符号要求但是会报当前注册有风险
![KV 7IMB}DE~X P(D4P}W7O9](https://github.com/Binaryify/NeteaseCloudMusicApi/assets/147133877/54bf610d-03f1-47e8-b60e-65aa6c72f243)

## 重现步骤
<请清晰描述重现步骤，调用的接口链接和参数以及命令行错误信息,最好贴上截图(命令行错误信息和接口返回内容)>

## 期待效果
<请清晰描述现在的效果和期待的效果>  
希望不用登入网易云账号也可以正常访问到歌曲的信息或者匿名用户能访问也行。
以及注册功能尽量能实现

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by XiejiHuang** [comment]
AxiosError {message: 'Request failed with status code 400', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
code
: 
"ERR_BAD_REQUEST"
config
: 
adapter
: 
Array(2)
0
: 
"xhr"
1
: 
"http"
length
: 
2
[[Prototype]]
: 
Array(0)
baseURL
: 
"http://localhost:8080/"
data
: 
undefined
env
: 
{FormData: ƒ, Blob: ƒ}
headers
: 
AxiosHeaders {Accept: 'application/json, text/plain, */*', Content-Type: null}
maxBodyLength
: 
-1
maxContentLength
: 
-1
method
: 
"get"
timeout
: 
0
transformRequest
: 
[ƒ]
transformResponse
: 
[ƒ]
transitional
: 
{silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false}
url
: 
"/playlist/track/all?id=596729952&timestamp=212562"
validateStatus
: 
ƒ validateStatus(status)
withCredentials
: 
true
xsrfCookieName
: 
"XSRF-TOKEN"
xsrfHeaderName
: 
"X-XSRF-TOKEN"
[[Prototype]]
: 
Object
message
: 
"Request failed with status code 400"
name
: 
"AxiosError"
request
: 
XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …}
response
: 
{data: {…}, status: 400, statusText: 'Bad Request', headers: AxiosHeaders, config: {…}, …}
stack
: 
"AxiosError: Request failed with status code 400\n    at settle (webpack-internal:///./node_modules/axios/lib/core/settle.js:24:12)\n    at XMLHttpRequest.onloadend (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:109:66)"
[[Prototype]]
: 
Error
控制台报错信息

**Comment by Binaryify** [comment]
试试 v4.13.6
