### ISSUE TITLE
在 Nextjs  中导入模块报错

### ISSUE THREAD

**Issue by oeyoews** [Binaryify/NeteaseCloudMusicApi#1842]
## 环境
- 系统/平台: Windows11

- nodejs 版本: 18

- API版本: 4.13.6

## 出现问题
在nextjs 中导入模块提示找不到

## 重现步骤

导入模块 `import { banner } from 'NeteaseCloudMusicApi';`

运行后提示

```
 ⨯ Error: ENOENT: no such file or directory, scandir 'D:\Workspace\react-music\.next\server\vendor-chunks\module'
    at Object.readdirSync (node:fs:1527:3)
    at __webpack_require__ (D:\Workspace\react-music\.next\server\webpack-runtime.js:33:43)
    at eval (./app/page.tsx:15:78)
    at (rsc)/./app/page.tsx (D:\Workspace\react-music\.next\server\app\page.js:505:1)
    at Function.__webpack_require__ (D:\Workspace\react-music\.next\server\webpack-runtime.js:33:43)
    at async Promise.all (index 0)
```

ps: 不知道是 这个NeteaseCloudMusicApi 包的问题, 还是nextjs 需要对这个包进行额外的配置 如果是在无框架的项目里require 调用模块, 都是正常的

## 期待效果
可以正常调用模块

---

>维护项目都是业余时间,精力有限,我只能挑容易解决的issues处理,为了节约双方时间,请尽可能提供足够的有用的信息,给的信息不够我只能根据精力和时间看情况处理,如果模板信息看都不看就删掉,我不会进行任何回复,并且一个月后close掉issue

>先看文档有没有相关说明,调用前须知必看,确认看完了调用前须知再发 issues

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或放着不管

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by oeyoews** [comment]
如果可以使用 nodejs 调用的话, 应该就不用额外搭建接口了

**Comment by oeyoews** [comment]
<img width="804" alt="image" src="https://github.com/Binaryify/NeteaseCloudMusicApi/assets/72405338/1860f2b5-9fa4-49a7-8a33-dd978f7c1261">
即使在nextjs 中使用require, 也提示找不到, 看起来像是需要额外配置一下webpack

**Comment by Binaryify** [comment]
这个只能服务端调用

**Comment by oeyoews** [comment]
在react 的服务端组件中不能用吗(不知道是不是这个服务端)

**Comment by EndyZhou** [comment]
`next.config.mjs` 添加  
```json
	  experimental: {
    serverComponentsExternalPackages: ["NeteaseCloudMusicApi"],
  },
```
