### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by XIAZY** [Binaryify/NeteaseCloudMusicApi#189]
### 环境
系统:  
4.13.0-32-generic #35~16.04.1-Ubuntu
nodejs 版本: 6.11.2

### 出现问题

```
REQUEST response end http://music.163.com/weapi/login/cellphone 200 { server: 'nginx',
  date: 'Mon, 05 Feb 2018 02:52:06 GMT',
  'content-type': 'application/json;charset=UTF-8',
  'content-length': '33',
  connection: 'keep-alive',
  vary: 'Accept-Encoding, Accept-Encoding',
  'cache-control': 'no-store, no-cache',
  pragrma: 'no-cache',
  expires: 'Thu, 01 Jan 1970 00:00:00 GMT',
  'x-via': 'MusicEdgeServer',
  'x-from-src': '35.202.227.84' }
REQUEST end event http://music.163.com/weapi/login/cellphone
REQUEST has body http://music.163.com/weapi/login/cellphone 33
REQUEST emitting complete http://music.163.com/weapi/login/cellphone
/home/ubuntu/NeteaseCloudMusicApi/router/loginCellphone.js:26
        cookie.push(item + ";Path=/");
              ^

TypeError: Cannot read property 'push' of undefined
    at cookieStr.split.forEach.item (/home/ubuntu/NeteaseCloudMusicApi/router/loginCellphone.js:26:15)
    at Array.forEach (native)
    at createWebAPIRequest (/home/ubuntu/NeteaseCloudMusicApi/router/loginCellphone.js:25:28)
    at Request._callback (/home/ubuntu/NeteaseCloudMusicApi/util/util.js:82:7)
    at Request.self.callback (/home/ubuntu/NeteaseCloudMusicApi/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/ubuntu/NeteaseCloudMusicApi/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
```
### 重现步骤
调用 /login/cellphone
### 期待效果
登录

**Comment by LaiLa06** [comment]
我也是这个出的问题，你是用的get还是post请求呀，我用postman测试的，他只能是get请求，可是怎么带phone和password呀

**Comment by XIAZY** [comment]
我用的是get，文档里是这么说的
为使用方便 , 降低门槛 , 登录接口直接使用了 get 明文请求 , 请按实际需求对源码修 改
