### ISSUE TITLE
一直报500错误

### ISSUE THREAD

**Issue by LaiLa06** [Binaryify/NeteaseCloudMusicApi#191]
### 环境
系统:  
win10
nodejs 版本:
v8.9.4
### 出现问题
TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:99:16)
    at router.get (E:\coding\vueMusic\NeteaseCloudMusicApi\router\loginCellphone.js:10:10)
    at Layer.handle [as handle_request] (E:\coding\vueMusic\NeteaseCloudMusicApi\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\coding\vueMusic\NeteaseCloudMusicApi\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\coding\vueMusic\NeteaseCloudMusicApi\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\coding\vueMusic\NeteaseCloudMusicApi\node_modules\express\lib\router\layer.js:95:5)
    at E:\coding\vueMusic\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\coding\vueMusic\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:335:12)
    at next (E:\coding\vueMusic\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:275:10)
    at expressInit (E:\coding\vueMusic\NeteaseCloudMusicApi\node_modules\express\lib\middleware\init.js:40:5)
### 重现步骤
发送登录请求（用postman测试能出现数据）
### 期待效果
有返回正确的数据

**Comment by LaiLa06** [comment]
解决了， 因为axios的get请求传参数的方式和post不同导致的
