### ISSUE TITLE
登录状态查询问题

### ISSUE THREAD

**Issue by BenXi630** [Binaryify/NeteaseCloudMusicApi#306]
登录状态查询出现问题，如果未登录，访问登录状态查询接口，会报错并且停止node

TypeError: Cannot read property '1' of null
    at createWebAPIRequest (C:\Users\W\Desktop\NeteaseCloudMusicApi-master\route
r\login_status.js:12:62)
    at Request._callback (C:\Users\W\Desktop\NeteaseCloudMusicApi-master\util\ut
il.js:86:7)
    at Request.self.callback (C:\Users\W\Desktop\NeteaseCloudMusicApi-master\nod
e_modules\_request@2.88.0@request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\W\Desktop\NeteaseCloudMusicApi-master\node_
modules\_request@2.88.0@request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\W\Desktop\NeteaseCloudMusicApi-mast
er\node_modules\_request@2.88.0@request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)

**Comment by Binaryify** [comment]
@nondanee

**Comment by nondanee** [comment]
哦哦好的晚上修😂

**Comment by BenXi630** [comment]
@thank you
