### ISSUE TITLE
关于android端启动API的问题

### ISSUE THREAD

**Issue by StageGuard** [Binaryify/NeteaseCloudMusicApi#413]
### 环境
系统:NeoTerm(Android)

nodejs 版本:v8.9.3

### 出现问题
$ node app.js
module.js:538
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/data/io.neoterm/files/home/NeteaseCloudMusicApi/NeteaseCloudMusicApi/app.js:3:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

### 重现步骤
node app.js

>用安卓终端应用NeoTerm运行api失败，，
node.js就是用的neoterm软件包里的node.js
不知道是api问题还是node.js的问题

**Comment by nondanee** [comment]
用 Termux 吧

**Comment by StageGuard** [comment]
谢谢，我去试试

**Comment by StageGuard** [comment]
@nondanee 太谢谢了，顺便新年快乐

**Comment by StageGuard** [comment]
@nondanee :sob:

```
$ npm install express
npm WARN saveError ENOENT: no such file or directory, open '/data/data/io.neoterm/files/home/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/data/data/io.neoterm/files/home/package.json'
npm WARN home No description
npm WARN home No repository field.
npm WARN home No README data
npm WARN home No license field.

+ express@4.16.4
updated 1 package and audited 273 packages in 5.758s
found 0 vulnerabilities

$
```

**Comment by nondanee** [comment]
@StageGuard 
没 cd 到 repo 目录中吧？`cd NeteaseCloudMusicApi`

全部步骤
```
git clone https://github.com/Binaryify/NeteaseCloudMusicApi.git
cd NeteaseCloudMusicApi
npm install
npm start
```

**Comment by StageGuard** [comment]
@nondanee 我觉得我没救了

```
$ ls
CHANGELOG.MD       docs               public
Dockerfile         issue_template.md  static
LICENSE            module             test
README.MD          node_modules       util
app.js             package-lock.json  yarn.lock
app.test.js        package.json
$ npm install express
npm WARN NeteaseCloudMusicApi@3.0.9 No repository field.

+ express@4.16.4
updated 1 package in 7.449s
$ ls
CHANGELOG.MD       docs               public
Dockerfile         issue_template.md  static
LICENSE            module             test
README.MD          node_modules       util
app.js             package-lock.json  yarn.lock
app.test.js        package.json
$ node app.js
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1379:14)
    at listenInCluster (net.js:1420:12)
    at Server.listen (net.js:1508:7)
    at Function.listen (/data/data/io.neoterm/files/home/NeteaseCloudMusicApi/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/data/data/io.neoterm/files/home/NeteaseCloudMusicApi/app.js:87:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
```

**Comment by StageGuard** [comment]
@nondanee 
终于可以了，谢谢
![](https://i.imgur.com/760LqNL.png)
