### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by Illyasviels** [Binaryify/NeteaseCloudMusicApi#462]
### 环境
系统: Win 10 64btis

nodejs 版本: 10.15.3

### 出现问题

```
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at split.forEach.pair (D:\Projects\NeteaseCloudMusicApi\app.js:41:72)
    at Array.forEach (<anonymous>)
    at app.use (D:\Projects\NeteaseCloudMusicApi\app.js:38:67)
    at Layer.handle [as handle_request] (D:\Projects\NeteaseCloudMusicApi\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Projects\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:317:13)
    at D:\Projects\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Projects\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Projects\NeteaseCloudMusicApi\node_modules\express\lib\router\index.js:275:10)
    at app.use (D:\Projects\NeteaseCloudMusicApi\app.js:33:5)
```

### 重现步骤

1. npm install
2. node app
3. http://localhost:3000/

### 期待效果

能进入首页

**Comment by Illyasviels** [comment]
清空缓存即可

**Comment by tuihou123321** [comment]
删除 app.js中的decodeURIComponent 即可

![image](https://user-images.githubusercontent.com/7146036/68862505-88987300-0728-11ea-9fd8-80f4cd690404.png)
