### ISSUE TITLE
win10 node app.js代码运行报错

### ISSUE THREAD

**Issue by acmweida** [Binaryify/NeteaseCloudMusicApi#482]
### 环境
系统: win10

nodejs 版本:10.15.3

### 出现问题

PS G:\MusicApi\NeteaseCloudMusicApi> node app.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (G:\MusicApi\NeteaseCloudMusicApi\app.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

### 期待效果

>重现步骤尽量详细,不能含糊不清

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>先在 issues 搜一下是否有相似问题，没有再发

**Comment by Binaryify** [comment]
你依赖没装

**Comment by acmweida** [comment]
需要nodejs 和 npm 还有其他依赖吗？

**Comment by Binaryify** [comment]
执行下 npm install

**Comment by acmweida** [comment]
可以了  非常 非常 感谢
