### ISSUE TITLE
$ node app.js 报错

### ISSUE THREAD

**Issue by 956569686** [Binaryify/NeteaseCloudMusicApi#623]
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './util/request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (E:\music\NeteaseCloudMusicApi-master\app.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! NeteaseCloudMusicApi@3.24.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the NeteaseCloudMusicApi@3.24.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by WhySuddenly** [comment]
同上

**Comment by 956569686** [comment]
用2.X的可以了
