### ISSUE TITLE
你好，代码在我的mac上没问题，但在cenos上运行不了

### ISSUE THREAD

**Issue by fuyifang** [Binaryify/NeteaseCloudMusicApi#80]
### 环境
系统:  
cenos 6 x86

nodejs 版本:
v0.10.48
mac v6.10.3可以使用

### 出现问题：
[root@host NeteaseCloudMusicApi]# node app.js 

/home/netease/NeteaseCloudMusicApi/app.js:245
app.listen(port,()=> {
                 ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

### 期待效果

**Comment by Binaryify** [comment]
你的nodejs版本太低了，要6.0+

**Comment by fuyifang** [comment]
我吧版本改成一样的还是报这个错误。。。

**Comment by fuyifang** [comment]
@Binaryify 我把版本改成一样的还是报这个错误。。。

**Comment by fuyifang** [comment]
都改成了v6.10.3 mac 上可以运行。。

**Comment by fuyifang** [comment]
可以用了，感谢api...
