### ISSUE TITLE
js 调用 song_url 无法接受字符串形式的 cookie

### ISSUE THREAD

**Issue by chenjunyu19** [Binaryify/NeteaseCloudMusicApi#812]
## 环境

- 系统/平台: Arch Linux x86_64
- nodejs 版本: v14.3.0
- API版本:3.32.2

## 出现问题

<https://github.com/Binaryify/NeteaseCloudMusicApi/blob/1a362242d4332d87cc2be0e264e2604ebefc4450/module/song_url.js#L5-L6>

```
发生异常: TypeError
TypeError: Cannot use 'in' operator to search for 'MUSIC_U' in MUSIC_U=***; Expires=Sun, 21-Jun-2020 11:12:58 GMT; Path=/;__remember_me=true; Expires=Sun, 21-Jun-2020 11:12:58 GMT; Path=/;__csrf=***; Expires=Sun, 21-Jun-2020 11:13:08 GMT; Path=/
    at module.exports (.../NeteaseCloudMusicApi/module/song_url.js:6:18)
    at obj.<computed> (.../NeteaseCloudMusicApi/main.js:10:12)
```

## 重现步骤

```javascript
const { song_url } = require(path.join(ncmApiPath, 'main.js'));
song_url({ id: array.join(','), cookie: 'MUSIC_U=***;......' });
```

## 其他

用 js 直接调用的话似乎大部分 api 都需要传入字符串形式的 cookie，而且 `login_cellphone` 的 `result.body.cookie` 也是字符串形式的。

**Comment by Binaryify** [comment]
已修复
