### ISSUE TITLE
在代理设置为UnblockNeteaseMusic的环境中运行, 无法正常调用借口

### ISSUE THREAD

**Issue by lenohard** [Binaryify/NeteaseCloudMusicApi#885]
## 环境
- 系统/平台: <你的系统和平台>
manjaro
- nodejs 版本: <你的 NodeJS 版本号>
v14.7.0
- API版本:<运行的云音乐 API 的版本号， 对应 package.json 里面的 version>
3.38.0
## 出现问题
<出现的问题>
无法正常调用接口
status: 502,
  body: {
    code: 502,
    msg: 'Error: unable to verify the first certificate\n' +
      '    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\n' +
      '    at TLSSocket.emit (events.js:314:20)\n' +
      '    at TLSSocket._finishInit (_tls_wrap.js:932:8)\n' +
      '    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)'
  }
}
## 重现步骤
<重现步骤>
运行UnblockNeteaseMusic在本地 127.0.0.1:80, 
sudo unblockneteasemusic -p 80:443 -f 59.111.181.35
设置终端代理也为这个地址
 export http_proxy="http://127.0.0.1:80"
 export https_proxy="http://127.0.0.1:80"
运行接口
node app.js
## 期待效果
<现在的效果，期待的效果>  
可以访问接口

>先看文档有没有相关说明,调用前须知必看

>先在 issues 搜一下是否有相似问题，没有再发,否则直接关闭

>不处理别人搭建的线上服务的问题,此项目不提供任何线上服务,请自行搭建

>重现步骤尽量详细,不能含糊不清，包含请求地址和对应参数以及操作过程描述,不是每个人都喜欢猜别人遇到了什么问题和找参数一个个试,也比较浪费时间

>如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

>460 cheating 的问题把 `utils/request.js` 里面的 `headers['X-Real-IP']` 的注释取消掉就好

**Comment by lenohard** [comment]
不属于这个仓库的问题
