### ISSUE TITLE
搜索接口一运行就报错

### ISSUE THREAD

**Issue by Shadownc** [Binaryify/NeteaseCloudMusicApi#98]
### 环境
系统:  
window
nodejs 版本:
6.10.0
### 出现问题
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)
### 重现步骤
调用搜索接口就报错
### 期待效果

**Comment by Limuyang1013** [comment]
亲测是Node版本的问题，我换成Node 8.5.0就OK了，或者换更高的应该也行，我之前用Node 6也有问题
