### ISSUE TITLE
node app.js运行报错

### ISSUE THREAD

**Issue by tuozhaobing** [Binaryify/NeteaseCloudMusicApi#99]
### 环境
系统:  MAC OS

nodejs 版本:4.5.0

### 出现问题
let cache = apicache.middleware
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
### 重现步骤
执行node app.js
### 期待效果

**Comment by Binaryify** [comment]
需要 NodeJS 6.0+ 环境

**Comment by tuozhaobing** [comment]
好的，我来升级下试试，这个可以直接部署在阿里云服务器上吗？

**Comment by Binaryify** [comment]
嗯

**Comment by tuozhaobing** [comment]
Thanks,我这边能正常运行了
